const ipData = {
  "27660": { name: "ABRIHAM AKELE GIZAW", callsign: "AK", position: "Head PTS " },
  "201033": { name: "B/GEN. H/SELASSIE GEBRU", callsign: "HS", position: "Asst.Head PTS" },
  "205171": { name: "WONDU KEDA KETO", callsign: "WN", position: "Asst.Head PTS AWA" },
  "31410": { name: "YOHANNES FEKADU SHIFERAW", callsign: "JO", position: "Chief FL.In" },
  "31416": { name: "ABNET TADELE TILAHUN", callsign: "AD", position: "Chief FL.In" },
  "31632": { name: "YOHANNES SHEMELES ", callsign: "YO", position: "A/Chief FL.In" },
  "31633": { name: "GELETA MITIKU TADESE", callsign: "GL", position: "A/Chief FL.In" },
  "15526": { name: "BERHANE WUBNEH TESFAYE", callsign: "BR", position: "Sr.FL.IN" },
  "23794": { name: "YITBAREK ADDIS KIDANU", callsign: "YT", position: "Sr.FL.IN" },
  "204486": { name: "CHANE TEFERI ", callsign: "CH", position: "Sr.FL.IN" },
  "27673": { name: "MEKDIM GETACHEW SAHILU", callsign: "MG", position: "Sr.FL.IN" },
  "31411": { name: "ROBEL TAMIRU GETACHEW", callsign: "RO", position: "Sr.FL.IN" },
  "31412": { name: "ABEL TSEGAYE WOLDESILASSIE", callsign: "LG", position: "Sr.FL.IN" },
  "31413": { name: "MULUGETA GAGA GASSA", callsign: "ME", position: "Sr.FL.IN" },
  "31414": { name: "MINTESNOT DEJENE FELEKE", callsign: "MJ", position: "Sr.FL.IN" },
  "31415": { name: "ABEL YIGEZU MEKONEN", callsign: "EL", position: "Sr.FL.IN" },
  "31539": { name: "MELAKU WONDIMU WOLDETSADIK", callsign: "LA", position: "Sr.FL.IN" },
  "27154": { name: "KUHLEN WELDU KASSAYE", callsign: "KU", position: "Fl.In" },
  "31629": { name: "SOLOMON ZEMEDKUN BELETE", callsign: "SZ", position: "Fl.In" },
  "31631": { name: "BISRAT GIRMA TESEMA", callsign: "BG", position: "Fl.In" },
  "31634": { name: "ABDULFETA NESREDIN NASSIR", callsign: "AZ", position: "Fl.In" },
  "31635": { name: "YIDNEKACHEW DEBEBE TEKLETSADIK", callsign: "YA", position: "Fl.In" },
  "31636": { name: "BINIAM ASSEFA GELAGAY", callsign: "BN", position: "Fl.In" },
  "31637": { name: "BINIYAM BELEW WONDEMAGEGN", callsign: "BB", position: "Fl.In" },
  "31638": { name: "YOHANNES MEKUANENT TAKELE", callsign: "YG", position: "Fl.In" },
  "31639": { name: "LEUL TSEGAYE HADDIS", callsign: "LT", position: "Fl.In" },
  "31640": { name: "NATNAEL FEKADU BERHANE", callsign: "NT", position: "Fl.In" },
  "31641": { name: "KIDUS RETA TADESSE", callsign: "KD", position: "Fl.In" },
  "31642": { name: "GEMECHIS ABERA BAISSA", callsign: "GM", position: "Fl.In" },
  "31643": { name: "BIRUK TEKABE HAILEMARIAM", callsign: "BK", position: "Fl.In" },
  "31644": { name: "AMANUEL AKALU MEKONNEN", callsign: "AU", position: "Fl.In" },
  "31645": { name: "BERHANESILASE TEMESGEN ABERA", callsign: "BM", position: "Fl.In" },
  "31646": { name: "HENOK KIBEBEW HABTEMARIAM", callsign: "HM", position: "Fl.In" },
  "31647": { name: "FIKERESILASSE MESFIN ABEBE", callsign: "FK", position: "Fl.In" },
  "31648": { name: "DAWIT MAEREGU BELAY", callsign: "DT", position: "Fl.In" },
  "31649": { name: "ABEBE MULUGETA ABEBE", callsign: "AA", position: "Fl.In" },
  "205137": { name: "YOHANNES HAGOS G/HIWOT  ", callsign: "YH", position: "Fl.In" },
  "205136": { name: "SOLOMON BEYENE W/MEDIHIN ", callsign: "SO", position: "Fl.In" },
  "205135": { name: "ASNAKE ABEBE AREGIE   ", callsign: "AS", position: "Fl.In" },
  "32140": { name: "MINTESNOT WOLDE GONFA", callsign: "MW", position: "Jr.Fl.In" },
  "32141": { name: "ANTENEH AMARE TADESSE", callsign: "AT", position: "Jr.Fl.In" },
  "32142": { name: "TEKLEHAYMANOT SEMU TESSEMA", callsign: "TK", position: "Jr.Fl.In" },
  "32143": { name: "KIRUBEL DANIEL BELAYNEH", callsign: "KR", position: "Jr.Fl.In" },
  "32144": { name: "EBISA TOLERA DIRO", callsign: "ET", position: "Jr.Fl.In" },
  "32145": { name: "NATENAEL SHEWAKENA CHERINET", callsign: "NS", position: "Jr.Fl.In" },
  "32146": { name: "ABENEZER SOLOMON DEGENE", callsign: "BZ", position: "Jr.Fl.In" },
  "32147": { name: "GETA BIYAZIN BEZE", callsign: "GZ", position: "Jr.Fl.In" },
  "32148": { name: "TEWFIQ MOHAMMED AHMED", callsign: "TM", position: "Jr.Fl.In" },
  "32149": { name: "MOHAMMED SEID SULEIMAN", callsign: "MS", position: "Jr.Fl.In" },
  "32150": { name: "ANDUAMLAKE WALELEGN ABATE", callsign: "AI", position: "Jr.Fl.In" },
  "32151": { name: "ABRHAM SOLOMON HAILU", callsign: "AL", position: "Jr.Fl.In" },
  "32152": { name: "ROBERA CHALCHISA BELISA", callsign: "RC", position: "Jr.Fl.In" },
  "32153": { name: "TEWODROS ABEBE WONDIMENEH", callsign: "TX", position: "Jr.Fl.In" },
  "32154": { name: "ABRAHAM ABEBAW DRESS", callsign: "AW", position: "Jr.Fl.In" },
  "32155": { name: "KALEAB GETACHEW BEYENE", callsign: "KG", position: "Jr.Fl.In" },
  "33128": { name: "YOHANNES TESFAYE GETACHEW", callsign: "YS", position: "Jr.Fl.In" },
  "33129": { name: "BIRUK KEBEDE GEMEDA", callsign: "BX", position: "Jr.Fl.In" },
  "33130": { name: "HABTAMU GIRMA DEMISSIE", callsign: "HU", position: "Jr.Fl.In" },
  "33131": { name: "KALEAB SAMUEL BEKELE", callsign: "SB", position: "Jr.Fl.In" },
  "33132": { name: "HENOK BIRHANU TEREFE", callsign: "HB", position: "Jr.Fl.In" },
  "33133": { name: "LEUL ATSBEHA REDA", callsign: "LD", position: "Jr.Fl.In" },
  "33134": { name: "ABENEZER TAYE ENGDA", callsign: "AV", position: "Jr.Fl.In" },
  "33135": { name: "ABDULKERIM MUSTEFA MOHAMOD", callsign: "AM", position: "Jr.Fl.In" },
  "33136": { name: "KIBROM BELAY ABADI", callsign: "KV", position: "Jr.Fl.In" },
  "33865": { name: "ABEL GEBREEGZIABHER HAILU", callsign: "AC", position: "Jr.Fl.In" },
  "33866": { name: "SAMUAL MULUGETA", callsign: "SL", position: "Jr.Fl.In" },
  "33867": { name: "MICHAEL MASRESHA HAILE", callsign: "MK", position: "Jr.Fl.In" },
  "33868": { name: "AMSALU TADESSE GEBRETSADIK", callsign: "AX", position: "Jr.Fl.In" },
  "33869": { name: "AMANUEL GETACHEW HAILU", callsign: "AH", position: "Jr.Fl.In" },
  "33870": { name: "SINTAYEHU TILAHUN HUNEGNAW", callsign: "SY", position: "Jr.Fl.In" },
  "33871": { name: "SURA MATHEWOS GETACHEW", callsign: "SR", position: "Jr.Fl.In" },
  "33872": { name: "SAMSON HAILU KASSA", callsign: "SN", position: "Jr.Fl.In" },
  "33873": { name: "MULUKEN AYALEW TEFERA", callsign: "MN", position: "Jr.Fl.In" },
  "33874": { name: "IMRAN FUAD AHMED", callsign: "IF", position: "Jr.Fl.In" },
  "33876": { name: "BETSELOT ELIAS HASSEN", callsign: "BE", position: "Jr.Fl.In" },
  "33877": { name: "EMANUEL GEBEYEHU NIGUSSIE", callsign: "EG", position: "Jr.Fl.In" },
  "33878": { name: "HABTAMU WEGAYEHU MEBRATE", callsign: "HA", position: "Jr.Fl.In" },
  "33879": { name: "GUTU ABEYA TEMESGEN", callsign: "GU", position: "Jr.Fl.In" },
  "33880": { name: "TEYIB KADI ABDURAHMAN", callsign: "TY", position: "Jr.Fl.In" },
  "34569": { name: "ABIY ZENA MARKOS", callsign: "NO", position: "Ass.Fl.In" },
  "34570": { name: "FERHAN KIFLE WORKU", callsign: "FE", position: "Ass.Fl.In" },
  "34571": { name: "ROBEL ABEBAW SIMENEH", callsign: "RL", position: "Ass.Fl.In" },
  "34572": { name: "AMEHA ABEBAW SENTIE", callsign: "AQ", position: "Ass.Fl.In" },
  "34573": { name: "HENOK DAMTEW TEKLEMARIAM", callsign: "HD", position: "Ass.Fl.In" },
  "34574": { name: "BERHANU WELDERUFAEL WELDEMESKEL", callsign: "BU", position: "Ass.Fl.In" },
  "34575": { name: "YIDNEKACHEW ARAGIE ASEFA", callsign: "YZ", position: "Ass.Fl.In" },
  "34576": { name: "ABRHAM TAKELE HAILEMESKEL", callsign: "JK", position: "Ass.Fl.In" },
  "34577": { name: "LEUL MEKONNEN ASSEFA", callsign: "LM", position: "Ass.Fl.In" },
  "34578": { name: "BAHIRAN BERGA MINOTA", callsign: "BW", position: "Ass.Fl.In" },
  "33579": { name: "RAEY TAYE WOLDERUFAEL", callsign: "RT", position: "Ass.Fl.In" },
  "35679": { name: "BROOK GETANEH BEKELE", callsign: "BY", position: "Ass.Fl.In" },
  "35680": { name: "ABDUREZAK ABDELA TESEMA", callsign: "EZ", position: "Ass.Fl.In" },
  "35681": { name: "DAGMAWI ABEBE SEIFU", callsign: "WI", position: "Ass.Fl.In" },
  "35682": { name: "BIRUK MESSERET MEKURIA", callsign: "MB", position: "Ass.Fl.In" },
  "35683": { name: "ZELALEM ADUGNA BEDADA", callsign: "ZA", position: "Ass.Fl.In" },
  "35684": { name: "ANATOLI YEMANE EJETA", callsign: "YL", position: "Ass.Fl.In" },
  "35685": { name: "DANIEL H/SELASSIE GEBRU", callsign: "DV", position: "Ass.Fl.In" },
  "36143": { name: "Ermias Mulat Zewdie ", callsign: "EM", position: "Ass.Fl.In" },
  "36144": { name: "Eyasu Hailesilassie Melake", callsign: "EH", position: "Ass.Fl.In" },
  "36145": { name: "Paulos Weldegebriel Assefa", callsign: "PW", position: "Ass.Fl.In" },
  "36146": { name: "Zekariyas Fekadu Germame", callsign: "ZO", position: "Ass.Fl.In" },
  "36147": { name: "Eyob Getachew Ayalew", callsign: "EY", position: "Ass.Fl.In" },
  "36148": { name: "Simgnew Esubalew Kebede", callsign: "SE", position: "Ass.Fl.In" },
  "36149": { name: "Gersam Zerihun Tesfaye", callsign: "GS", position: "Ass.Fl.In" },
  "36150": { name: "Dagnachew Abera Regassa", callsign: "DC", position: "Ass.Fl.In" },
  "36151": { name: "Matiyos Teklu Mergiya", callsign: "MT", position: "Ass.Fl.In" },
  "36152": { name: "Daniel Anbelu Tebeje", callsign: "DN", position: "Ass.Fl.In" },
  "36153": { name: "Mohammed Hassen Ahmed", callsign: "MO", position: "Ass.Fl.In" },
  "36154": { name: "Getnet Gezahegn Engida", callsign: "GN", position: "Ass.Fl.In" },
  "36155": { name: "Israel Teshome Zewde", callsign: "IZ", position: "Ass.Fl.In" },
};